# -*- coding: utf-8 -*-
"""Tugas 13 PCD Kelompok 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwhvLXVZbNgKbEEi3fhVyvgZppI56WnB

IMAGE SECURITY – Citra Medis (X-Ray)
Bagian A – Analisis Singkat
1. Deskripsi Kasus

Citra medis seperti X-Ray digunakan untuk diagnosis kondisi tulang belakang (misalnya skoliosis atau pasca operasi pemasangan implant). Citra ini termasuk data medis sensitif yang bersifat rahasia dan dilindungi secara hukum.

2. Jenis Citra

Jenis: Citra medis X-Ray

Format umum: JPG / PNG / DICOM

Sifat citra:

Grayscale

Detail tinggi

Mengandung informasi pribadi pasien.


3. Alasan Perlu Diamankan

Mengandung data kesehatan pribadi

Digunakan sebagai dasar diagnosis

Harus memenuhi prinsip kerahasiaan, integritas, dan ketersediaan data.


4. Ancaman Keamanan

Akses ilegal oleh pihak tidak berwenang

Pencurian data medis

Manipulasi citra (pemalsuan hasil medis)

Penyadapan saat transmisi data.


5. Risiko Kebocoran / Manipulasi

Diagnosis medis yang salah

Pelanggaran privasi pasien

Kerugian hukum bagi rumah sakit

Penyalahgunaan data kesehatan.



6. Dampak yang Ditimbulkan

Kesalahan tindakan medis

Kehilangan kepercayaan pasien

Sanksi hukum

Kerusakan reputasi institusi kesehatan.



7. Solusi Keamanan
Pendekatan yang digunakan:

Enkripsi citra → Melindungi isi gambar

Steganografi → Menyembunyikan informasi sensitif (misalnya ID pasien).



8. Alasan Pemilihan Metode

Enkripsi: Data tidak dapat dibaca tanpa kunci

Steganografi: Informasi tersembunyi tidak terlihat oleh pihak lain

Mudah diimplementasikan dengan Python

Cocok untuk pembelajaran konsep dasar keamanan citra.
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load citra X-Ray
img = cv2.imread('/content/X--ray skoliosis.jpg', cv2.IMREAD_GRAYSCALE)

# Periksa apakah citra berhasil dimuat
if img is None:
    print('Error: Citra tidak dapat dimuat. Periksa jalur file atau nama file.')
else:
    plt.imshow(img, cmap='gray')
    plt.title('Citra X-Ray Asli')
    plt.axis('off')

# Kunci enkripsi
key = 123

# Enkripsi menggunakan XOR
encrypted_img = img ^ key

plt.imshow(encrypted_img, cmap='gray')
plt.title('Citra Terenkripsi')
plt.axis('off')

# Dekripsi menggunakan key yang sama
decrypted_img = encrypted_img ^ key

plt.imshow(decrypted_img, cmap='gray')
plt.title('Citra Hasil Dekripsi')
plt.axis('off')

def text_to_bin(text):
    return ''.join(format(ord(c), '08b') for c in text)

def embed_message(image, message):
    binary_msg = text_to_bin(message) + '1111111111111110'
    img_flat = image.flatten()

    for i in range(len(binary_msg)):
        img_flat[i] = (img_flat[i] & 254) | int(binary_msg[i])

    return img_flat.reshape(image.shape)

secret_message = "ID_PASIEN_12345"
stego_img = embed_message(img, secret_message)

plt.imshow(stego_img, cmap='gray')
plt.title('Citra dengan Pesan Tersembunyi')
plt.axis('off')

def extract_message(image):
    img_flat = image.flatten()
    binary_msg = ""

    for pixel in img_flat:
        binary_msg += str(pixel & 1)

    chars = [binary_msg[i:i+8] for i in range(0, len(binary_msg), 8)]
    message = ""

    for char in chars:
        if char == '11111111':
            break
        message += chr(int(char, 2))

    return message

print("Pesan tersembunyi:", extract_message(stego_img))