# -*- coding: utf-8 -*-
"""Tugas 13 PCD Kelompok 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwhvLXVZbNgKbEEi3fhVyvgZppI56WnB
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load citra X-Ray
img = cv2.imread('/content/X--ray skoliosis.jpg', cv2.IMREAD_GRAYSCALE)

# Periksa apakah citra berhasil dimuat
if img is None:
    print('Error: Citra tidak dapat dimuat. Periksa jalur file atau nama file.')
else:
    plt.imshow(img, cmap='gray')
    plt.title('Citra X-Ray Asli')
    plt.axis('off')

# Kunci enkripsi
key = 123

# Enkripsi menggunakan XOR
encrypted_img = img ^ key

plt.imshow(encrypted_img, cmap='gray')
plt.title('Citra Terenkripsi')
plt.axis('off')

# Dekripsi menggunakan key yang sama
decrypted_img = encrypted_img ^ key

plt.imshow(decrypted_img, cmap='gray')
plt.title('Citra Hasil Dekripsi')
plt.axis('off')

def text_to_bin(text):
    return ''.join(format(ord(c), '08b') for c in text)

def embed_message(image, message):
    binary_msg = text_to_bin(message) + '1111111111111110'
    img_flat = image.flatten()

    for i in range(len(binary_msg)):
        img_flat[i] = (img_flat[i] & 254) | int(binary_msg[i])

    return img_flat.reshape(image.shape)

secret_message = "ID_PASIEN_12345"
stego_img = embed_message(img, secret_message)

plt.imshow(stego_img, cmap='gray')
plt.title('Citra dengan Pesan Tersembunyi')
plt.axis('off')

def extract_message(image):
    img_flat = image.flatten()
    binary_msg = ""

    for pixel in img_flat:
        binary_msg += str(pixel & 1)

    chars = [binary_msg[i:i+8] for i in range(0, len(binary_msg), 8)]
    message = ""

    for char in chars:
        if char == '11111111':
            break
        message += chr(int(char, 2))

    return message

print("Pesan tersembunyi:", extract_message(stego_img))